config/routes.rb
RailsSite::Application.routes.draw do

	get "test/one"
	get "test/two"
	get "test/three"
	get "test/four"
	get "intersital/index"
	namespace :deposits do
		post "form_submit"
		post "set_express_checkout_paypal"
		get "do_express_checkout_paypal"
		post "set_express_checkout_payza"
	end

	get "advertiser", to:"advertisers#index"
	get "advertiser/wallet", to:"advertisers#wallet"
	get "advertiser/wallet/page/:page_number", to:"advertisers#wallet", constraints: {:page_number => /[0-9]+/}
	get "advertiser/campaign", to:"advertisers#campaign"
	get "advertiser/create_ad", to:"advertisers#create_ad"
	post "advertiser/create_ad", as:"advertiser_create_ad_post", to:"advertisers#create_ad_post"
	post "advertiser/destroy_ad/:id", as:"advertiser_destroy_ad", to:"advertisers#destroy_ad", id: /[0-9]+/
	post "advertiser/create_ad_preview", to:"advertisers#create_ad_preview"
	get "advertiser/create_ad/design/:id", to:"advertisers#design_ad", id: /[0-9]+/, as: "advertiser_design_ad"
	post "advertiser/create_ad/design/:id", to:"advertisers#design_ad", id: /[0-9]+/, as: "advertiser_design_ad_post"
	get "advertiser/create_ad/clone/:id", to:"advertisers#clone_ad", id: /[0-9]+/, as: "advertiser_clone_ad"
	post "advertiser/create_ad/clone/:id", to:"advertisers#clone_ad", id: /[0-9]+/, as: "advertiser_clone_ad_post"
	get "advertiser/account",  to:"advertisers#account"

	resources :announcements

	get  "r/:referer_key", to: "referal#initiate", constraints:{ referer_key: /[-~_.0-9A-Za-z]{4}/ }, as: "referal_init"
	post "referal/create"
	post "referal/destroy"

	root "welcome#index"

	get   "welcome/index"
	get   ":who/learn_more", to: "welcome#learn_more", as: :welcome_learn_more, constraints: {who: /publisher|advertiser|pub|adv/}

	namespace :url_action do
		post "shrink"
		post ":id/destroy", as: :destroy, action: :destroy
		post "update_urls"
		post "mass_shrink"
		post "multi_links_shrink"
	end

	resource :users
	post  "users/login", as: "login_users"
	post  "users/logout", as: "logout_users"
	post  "user/google_analytics/add", to: "users#add_google_analytics", as: "add_google_analytics"
	post  "user/google_analytics/destroy", to: "users#destroy_google_analytics", as: "destroy_google_analytics"

	get   "u", as: "user_home", to: "users#home"
	get   "u/dashboard", to: "users#home"
	get   "u/referals", to: "users#referals"
	get   "u/tools", to: "users#tools"
	get   "u/withdraw", to: "users#withdraw"
	get   "u/account", to: "users#account"

	get  "api/user_id/:user_id/api_key/:api_key/url/*url", to: "url_action#api", constraints:{api_key: /\w{64}/, user_id: /[0-9]+/, url: /(http\:\/|https\:\/|)\w+[.]{1}\w+([.]{1}\w+|)+(\/.+|)/}, format: false
	get  "api/get", to: "url_action#api", format: false
	post "api/post", to: "url_action#api", format: false

	get "tests", to: "url_action#test"

	get  "bookmarklet/*url", to: "url_action#bookmarklet", format: false

	get  ":user_id/*url", to: "url_action#easy_link", as: "easy_link", constraints:{user_id: /[0-9]+[+]{1}/, url: /((http\:\/|https\:\/|)\w+[.]{1}\w+([.]{1}\w+|)+(\/.+|))|http:\/localhost\:3000\/tests/}, format: false
	get  ":user_id/:digest_url", to: "url_action#digest_easy_link", as: "digest_easy_link", constraints:{user_id: /[+]{1}[0-9]+/, digest_url: /\w{32}/}, format: false

	get   "intersital/generate/:id", to: "intersital#generate_ad", constraints:{ id: /[0-9]+/ }, as: :generate_intersital
	get   "intersital/generate/preview/:id", to: "intersital#generate_ad_preview", constraints:{ id: /[0-9]+/ }, as: :generate_intersital_preview
	post  "intersital/request_campaign", to: "intersital#request_campaign"
	get   ":key", to: "intersital#index", constraints:{ key: /[-~_.0-9A-Za-z]{4}/ }

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
	before_action :set_announcement, only: [:show, :edit, :update, :destroy]

	# GET /announcements
	# GET /announcements.json
	def index
		@announcements = Announcement.all
	end

	# GET /announcements/1
	# GET /announcements/1.json
	def show
	end

	# GET /announcements/new
	def new
		@announcement = Announcement.new
	end

	# GET /announcements/1/edit
	def edit
	end

	# POST /announcements
	# POST /announcements.json
	def create
		@announcement = Announcement.new(announcement_params)

		respond_to do |format|
			if @announcement.save
				format.html { redirect_to @announcement, notice: 'Announcement was successfully created.' }
				format.json { render action: 'show', status: :created, location: @announcement }
			else
				format.html { render action: 'new' }
				format.json { render json: @announcement.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /announcements/1
	# PATCH/PUT /announcements/1.json
	def update
		respond_to do |format|
			if @announcement.update(announcement_params)
				format.html { redirect_to @announcement, notice: 'Announcement was successfully updated.' }
				format.json { head :no_content }
			else
				format.html { render action: 'edit' }
				format.json { render json: @announcement.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /announcements/1
	# DELETE /announcements/1.json
	def destroy
		@announcement.destroy
		respond_to do |format|
			format.html { redirect_to announcements_url }
			format.json { head :no_content }
		end
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_announcement
			@announcement = Announcement.find(params[:id])
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def announcement_params
			params.require(:announcement).permit(:title, :body, :for)
		end
	end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_form.html.erb
<%= form_for(@announcement) do |f| %>
  <% if @announcement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>

      <ul>
      <% @announcement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div class="field">
    <%= f.label :for %><br>
    <%= f.text_field :for %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/announcements/edit.html.erb
<h1>Editing announcement</h1>

<%= render 'form' %>

<%= link_to 'Show', @announcement %> |
<%= link_to 'Back', announcements_path %>

app/views/announcements/index.html.erb
<h1>Listing announcements</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>For</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @announcements.each do |announcement| %>
      <tr>
        <td><%= announcement.title %></td>
        <td><%= announcement.body %></td>
        <td><%= announcement.for %></td>
        <td><%= link_to 'Show', announcement %></td>
        <td><%= link_to 'Edit', edit_announcement_path(announcement) %></td>
        <td><%= link_to 'Destroy', announcement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Announcement', new_announcement_path %>

app/views/announcements/new.html.erb
<h1>New announcement</h1>

<%= render 'form' %>

<%= link_to 'Back', announcements_path %>

app/views/announcements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @announcement.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @announcement.body %>
</p>

<p>
  <strong>For:</strong>
  <%= @announcement.for %>
</p>

<%= link_to 'Edit', edit_announcement_path(@announcement) %> |
<%= link_to 'Back', announcements_path %>