config/routes.rb
RailsSite::Application.routes.draw do

	get "test/one"
	get "test/two"
	get "test/three"
	get "test/four"
	get "intersital/index"
	namespace :deposits do
		post "form_submit"
		post "set_express_checkout_paypal"
		get "do_express_checkout_paypal"
		post "set_express_checkout_payza"
	end

	get "advertiser", to:"advertisers#index"
	get "advertiser/wallet", to:"advertisers#wallet"
	get "advertiser/wallet/page/:page_number", to:"advertisers#wallet", constraints: {:page_number => /[0-9]+/}
	get "advertiser/campaign", to:"advertisers#campaign"
	get "advertiser/create_ad", to:"advertisers#create_ad"
	post "advertiser/create_ad", as:"advertiser_create_ad_post", to:"advertisers#create_ad_post"
	post "advertiser/destroy_ad/:id", as:"advertiser_destroy_ad", to:"advertisers#destroy_ad", id: /[0-9]+/
	post "advertiser/create_ad_preview", to:"advertisers#create_ad_preview"
	get "advertiser/create_ad/design/:id", to:"advertisers#design_ad", id: /[0-9]+/, as: "advertiser_design_ad"
	post "advertiser/create_ad/design/:id", to:"advertisers#design_ad", id: /[0-9]+/, as: "advertiser_design_ad_post"
	get "advertiser/create_ad/clone/:id", to:"advertisers#clone_ad", id: /[0-9]+/, as: "advertiser_clone_ad"
	post "advertiser/create_ad/clone/:id", to:"advertisers#clone_ad", id: /[0-9]+/, as: "advertiser_clone_ad_post"
	get "advertiser/account",  to:"advertisers#account"

	resources :announcements

	get  "r/:referer_key", to: "referal#initiate", constraints:{ referer_key: /[-~_.0-9A-Za-z]{4}/ }, as: "referal_init"
	post "referal/create"
	post "referal/destroy"

	root "welcome#index"

	get   "welcome/index"
	get   ":who/learn_more", to: "welcome#learn_more", as: :welcome_learn_more, constraints: {who: /publisher|advertiser|pub|adv/}

	namespace :url_action do
		post "shrink"
		post ":id/destroy", as: :destroy, action: :destroy
		post "update_urls"
		post "mass_shrink"
		post "multi_links_shrink"
	end

	resource :users
	post  "users/login", as: "login_users"
	post  "users/logout", as: "logout_users"
	post  "user/google_analytics/add", to: "users#add_google_analytics", as: "add_google_analytics"
	post  "user/google_analytics/destroy", to: "users#destroy_google_analytics", as: "destroy_google_analytics"

	get   "u", as: "user_home", to: "users#home"
	get   "u/dashboard", to: "users#home"
	get   "u/referals", to: "users#referals"
	get   "u/tools", to: "users#tools"
	get   "u/withdraw", to: "users#withdraw"
	get   "u/account", to: "users#account"

	get  "api/user_id/:user_id/api_key/:api_key/url/*url", to: "url_action#api", constraints:{api_key: /\w{64}/, user_id: /[0-9]+/, url: /(http\:\/|https\:\/|)\w+[.]{1}\w+([.]{1}\w+|)+(\/.+|)/}, format: false
	get  "api/get", to: "url_action#api", format: false
	post "api/post", to: "url_action#api", format: false

	get "tests", to: "url_action#test"

	get  "bookmarklet/*url", to: "url_action#bookmarklet", format: false

	get  ":user_id/*url", to: "url_action#easy_link", as: "easy_link", constraints:{user_id: /[0-9]+[+]{1}/, url: /((http\:\/|https\:\/|)\w+[.]{1}\w+([.]{1}\w+|)+(\/.+|))|http:\/localhost\:3000\/tests/}, format: false
	get  ":user_id/:digest_url", to: "url_action#digest_easy_link", as: "digest_easy_link", constraints:{user_id: /[+]{1}[0-9]+/, digest_url: /\w{32}/}, format: false

	get   "intersital/generate/:id", to: "intersital#generate_ad", constraints:{ id: /[0-9]+/ }, as: :generate_intersital
	get   "intersital/generate/preview/:id", to: "intersital#generate_ad_preview", constraints:{ id: /[0-9]+/ }, as: :generate_intersital_preview
	post  "intersital/request_campaign", to: "intersital#request_campaign"
	get   ":key", to: "intersital#index", constraints:{ key: /[-~_.0-9A-Za-z]{4}/ }

end

app/models/user.rb
require 'Base66'

class EmailValidator < ActiveModel::EachValidator
	def validate_each(record, attribute, value)
		unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
			record.errors[attribute] << (options[:message] || 'is not an email')
		end
	end
end

class PasswordValidator < ActiveModel::EachValidator
	def validate_each(record, attribute, value)
		if (value =~ /[0-9]+/).nil? || (value =~ /[a-z]+/).nil? || (value =~ /[A-Z]+/).nil?
			record.errors[attribute] << (options[:message] || "must contain at least 1 lowercase, 1 uppercase and 1 number")
		end
	end
end

class User < ActiveRecord::Base
	has_many :url

	after_create :digest_password
	validates :full_name, :email, :password, presence: true
	validates :full_name, length: { in: 5..50 }
	validates :email, uniqueness: true, email: true
	### Create validation for password ###

	def get_api_key
		if api_key.nil?
			api_key_ = Digest::MD5.hexdigest "USER_ID=#{id}&TIMESTAMP=#{Time.now.to_s}&RAND_NUM=#{Random.new.rand(1000)}"
			update api_key: api_key_
		else
			api_key_ = api_key
		end
		api_key_
	end

	private
		def digest_password
			update password: Digest::MD5.hexdigest(self.password)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :login_check, only: [:home, :tools, :add_google_analytics, :destroy_google_analytics]
	before_action :redirect_to_http, only: [:home]

	def home
		#@ip = request.remote_ip      #Gets the ip of the visitor which allows to get location
		@layout_details = {
			controller: params[:controller],
			action: params[:action],
			other_styles: [],
			other_scripts: [],
			title: 'ily.io'
		}
		@new_urls = get_urls
		@announcements = Announcement.where for: %q{p}    # for: "p" || :for => "p"
	end

	def login
		@error = false
		@password = get_user_login_params[:password]
		@email    = get_user_login_params[:email]
		@find_user= User.find_by(email: @email)
		if !@find_user.nil?
			@db_pass  = @find_user.password
			if @db_pass == @password
				@user = User.find_by(email: @email)
				session[:user_id] = @user.id
			else
				@error = true
				flash[:error] = "Wrong password inserted<br />Check if caps lock is on and try again"
			end
		else
			@error = true
			flash[:error] = "Email does not exist in our database<br />Please, register first"
		end

		if @error
			redirect_to root_path
		else
			redirect_to user_home_path
		end
	end

	def logout
		session.delete(:user_id)
		redirect_to root_path
	end

	def create
		@user = User.new(get_user_register_params)
		@user.save
		if @user.errors.any?
			flash[:error] = @user.errors.full_messages.join("<br />")
		else
			session[:user_id] = @user.id
		end
		redirect_to root_path # not user_home_path since there might be errors
	end

	def referals
		render text: 'Ok'
	end

	def add_google_analytics
		@tracker_code = params.require(:google_analytics).permit(:tracker_code)[:tracker_code]
		if UserOtherDetail.find_by(user_id: session[:user_id]).nil?
			@user_add_analytics = UserOtherDetail.new({tracker_code: @tracker_code, user_id: session[:user_id]})
			@user_add_analytics.save
		else
			@current_record = UserOtherDetail.find_by(user_id: session[:user_id])
			@current_record.tracker_code = @tracker_code
			@current_record.save
		end
		redirect_to u_tools_path
	end

	def destroy_google_analytics
		if !UserOtherDetail.find_by(user_id: session[:user_id]).nil?
			@current_record = UserOtherDetail.find_by(user_id: session[:user_id])
			@current_record.destroy
			redirect_to u_tools_path
		end
	end

	def tools
		@layout_details = {
			controller: params[:controller],
			action: params[:action],
			other_styles: [],
			other_scripts: [],
			title: 'ily.io'
		}
	end

	def withdraw
		@layout_details = {
			controller: params[:controller],
			action: params[:action],
			other_styles: [],
			other_scripts: [],
			title: 'ily.io'
		}
	end

	def account
		@layout_details = {
			controller: params[:controller],
			action: params[:action],
			other_styles: [],
			other_scripts: [],
			title: 'ily.io'
		}
	end

	def new
	end

	def edit
	end

	def show
	end

	def update
	end

	def destroy
	end

	private

		def login_check
			if session[:user_id].nil?
				redirect_to root_path
			else
				@name = User.find(session[:user_id]).full_name
			end
		end

		def get_user_login_params
			@params = params.require(:user_login).permit(:email, :password)
			@password = Digest::MD5.hexdigest(@params[:password])
			@params[:password] = @password
			@params
		end

		def get_user_register_params
			params.require(:user_register).permit(:full_name, :email, :password)
		end

		def get_urls
			urls = Array.new
			urls = Url.where(:user_id => session[:user_id])
			new_urls = Array.new
			if urls.size > 0
				pages = 1..(urls.size / 10.0).ceil
				pages.each do |page|
					x = (page-1)*10
					array = Array.new
					if page == pages.end
						if urls.length % 10 == 0
							y = x + 9
						else
							y = x - 1 + (urls.length % 10)
						end
						(x..y).each do |i|
							array << urls[i]
						end
					else
						y = x + 9
						(x..y).each do |i|
							array << urls[i]
						end
					end
					new_urls << array
				end
			end
			new_urls
		end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/account.html.erb
Account

app/views/users/home.html.erb
<div id="brief_stats">
	<table>
		<tr>
			<td>
				<div>
					<div>Views today</div>
					<div>223</div>
				</div>
			</td>
			<td>
				<div>
					<div>Earnings today</div>
					<div>$ 2.23</div>
				</div>
			</td>
			<td>
				<div>
					<div>Total views</div>
					<div>12300</div>
				</div>
			</td>
			<td>
				<div>
					<div>Total earnings</div>
					<div>$ 12.30</div>
				</div>
			</td>
		</tr>
	</table>
</div>

<div id="shorten">
	<div class="heading">Shrink link now !</div>
	<div>
		<div id="scrollable">
			<div id="shrink_div">
				<%= form_for :shrink, url: url_action_shrink_path, html:{ id: "shrink_form" } do |f| %>
					<div>
						<div class="left"><%= f.text_field :target, class: "textInput", placeholder: "http://" %></div>
						<div class="left"><%= f.submit "Shrink", id: :shrink_button, class: "button" %></div>
					</div>
				<% end %>
			</div>
			<div id="shorten_div">
				<textarea id="shorten_textarea"></textarea>
				<div id="try_another_div"></div>
			</div>
		</div>
	</div>
</div>

<div id="announcements">
	<div class="heading">
		Announcements and updates
	</div>
	<marquee>
		<div>
			<% @announcements.each do |announcement| %>
			<div class="left">
				<span><strong>**&nbsp;<%= announcement.title %>&nbsp;**&nbsp;:&nbsp;</strong></span><span><%= announcement.body %></span><span><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong></span>
			</div>
			<% end %>
		</div>
	</marquee>
</div>

<div id="links">
	<div class="heading">Manage your links</div>
    <div id="links_list">
        <div>
            <table>
                <tr>
                    <td width="30px"><div><strong>&nbsp;</strong></div></td>
                    <td width="50px"><div><strong>#</strong></div></td>
                    <td width="190px"><div><strong>short url</strong></div></td>
                    <td width="240px"><div><strong>target link</strong></div></td>
                    <td width="100px"><div><strong># of views</strong></div></td>
                    <td width="100px"><div><strong>net earning</strong></div></td>
                    <td width="70px"><div><strong>&nbsp;</strong></div></td>
                </tr>
            </table>
            <div id="slideable">
                <% unless @new_urls.empty? %>
                    <% count = 0 %>
                    <% @new_urls.each do |page| %>
                        <div id="<% if count == 0 %>first_table<% end %>" class="tables">
                            <table>
                                <% page.each do |url| %>
                                    <% count += 1 %>
                                    <tr data-urlid="<%= url.id %>">
                                        <td width="30px"><div>&nbsp;<input name="url_id" value="<%= url.id %>" type="checkbox" /></div></td>
                                        <td width="50px"><div><%= count %>.</div></td>
                                        <td width="190px"><div><a target="_blank" href="/<%= url.key %>">http://ily.io/<%= url.key %></a></div></td>
                                        <td width="240px"><div><a target="_blank" href="<%= url.target %>"><%= url.target %></a></div></td>
                                        <td width="100px"><div><%= url.views %></div></td>
                                        <td width="100px"><div>$0.00</div></td>
                                        <td width="70px"><div><a class="delete" href="<%= url_action_destroy_path(url.id) %>" data-number="<%= count %>" data-urlid="<%= url.id %>">delete</a></div></td>
                                    </tr>
                                <% end %>
                            </table>
                        </div>
                    <% end %>
                <% end %>
                <div class="<%= @new_urls.empty? ? nil : "nodisplay" %>" id="inside_slideable_when_first_time">
                    <div style="padding: 0 10px">
                        <strong>You have not shrink any url yet.??</strong><br />
                        <strong> - Watch the video to get started...</strong>
                    </div>
                    <div>
                        <video id="get_started_video" width="320" height="240" controls>
                            <source src="" type="video/mp4" />
                            <source src="" type="video/webm" />
                            <source src="" type="video/ogg" />
                            Your browser does not support the video tag.
                        </video>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="next_prev">
        <button id="prev_button" class="button">Previous page</button>
        <button id="next_button" class="button">Next page</button>
    </div>
</div>

app/views/users/tools.html.erb

<div id="tool_list_div">
	<div class="tools selected" data-name="ms">Mass shrinker&nbsp;&nbsp;&nbsp;&rarr;</div>
	<div class="tools" data-name="mls">Multi-links shrinker&nbsp;&nbsp;&nbsp;&rarr;</div>
	<div class="tools" data-name="b">Bookmarklet&nbsp;&nbsp;&nbsp;&rarr;</div>
	<div class="tools" data-name="api">API Doc&nbsp;&nbsp;&nbsp;&rarr;</div>
	<div class="tools" data-name="ga">Google analytics&nbsp;&nbsp;&nbsp;&rarr;</div>
	<div class="tools" data-name="el">Easy link&nbsp;&nbsp;&nbsp;&rarr;</div>
	<div class="tools" data-name="wes">Website entry script&nbsp;&nbsp;&nbsp;&rarr;</div>
</div>
<div id="tool_div">
	<div id="ms_div">
		<div class="tool_title heading">Mass Shrinker</div>
		<div class="tool_desc">
			Mass shrinker allows you to shrink up to 25 urls in a single go.<br /><br />
			[<b class="green">Note:</b> Each url must begin on a new line]
		</div>
		<div id="ms_tool_textarea">
			<textarea></textarea>
		</div>
		<div id="ms_shrink"><button class="button">Shrink</button></div>
	</div>
	<div class="nodisplay" id="el_div">
		<div class="tool_title heading">Easy Link</div>
		<div class="tool_desc">
			Easy link allows you to access our intersital ad service without the need to actually shrink your url.
		</div>
		<div id="el_usage_div">
			<div><strong class="red">Format</strong></div>
			<div>
				http://ily.io/&lt; your user id &gt;<b>+</b>/&lt; the destination url &gt;
			</div>
			<div><br />
				Your user id is <b style="color:red"><%= session[:user_id] %></b><br/>
				[<b class="green">Note:</b> Do not forget the plus(+) sign after user id]<br />
				<strong class="red">An example to google.com will be</strong>
			</div>
			<div>
				http://ily.io/<%= session[:user_id] %><b>+</b>/google.com
				<br />
				<b>or</b>
				<br />
				http://ily.io/<%= session[:user_id] %><b>+</b>/www.google.com
				<br />
				<b>or</b>
				<br />
				http://ily.io/<%= session[:user_id] %><b>+</b>/http://google.com
			</div>
			<div><br />
				Remember that the destination url should be hidden to the user.<br />
				<b class="red">Example</b>
			</div>
			<div>
				&lt;a href="http://ily.io/<%= session[:user_id] %><b>+</b>/google.com"&gt;Go to page&lt;/a&gt;
				<br />
				<b>see below</b>
				<br />
				<a href="/<%= session[:user_id] %>+/google.com">Go to page</a>
			</div>
			<div><br />
				On accessing the link, the url will be instantly changed such that user will not be able to know the destion url.<br />
				<b class="red">Example</b>
			</div>
			<div>
				http://ily.io/<%= session[:user_id] %><b>+</b>/google.com
				<br />
				<b>becomes</b>
				<br />
				http://ily.io/+<%= session[:user_id] %>/1d5920f4b44b27a802bd77c4f0536f5a
			</div>
			<div><br />
				<b class="red">** Remember **</b>
				The use of easy link is not a very reliable way to optimize your revenue since some visitors can bypass the link lock system by viewing the source of the site/blog/forum on which the easy link is shared.
			</div>
		</div>
	</div>
	<div class="nodisplay" id="b_div">
		<div class="tool_title heading">Bookmarklet</div>
		<div class="tool_desc">
			The bookmarklet tool allows you to shrink the url of the site you are visiting by just a single click on the bookmarklet.<br /><br />
			<b class="red">How to set up?</b><br />
			Simply drag and drop the following link to your bookmark bar.
			<div class="framed"><b><a href="javascript:void(location.href='http://localhost:3000/bookmarklet/'+encodeURIComponent(location.href))">ily.io Bookmarklet</a></b></div>  <!-- CHANGE -> localhost:3000 to ily.io -->
			<br />
			<b class="red">How to use?</b><br />
			Simply click on the "ily.io Bookmarklet" while visiting the page's URL you want to shrink.<br />
			<br />
			[<b class="green">Note:</b> You must be logged in order for the bookmarklet to work]
		</div>
	</div>
	<div class="nodisplay" id="api_div">
		<div class="tool_title heading">API Doc</div>
		<div class="tool_desc">
			The API tool allows you to shrink URLs without the need to log in ily.io<br />Simply send a GET or POST request to our server using your API key.<br /><br />
			<b>Your user id is </b><b style="color:red"><%= session[:user_id] %></b><br /><br />
			<b>Your API key(64 characters) below</b><br />
			<div class="framed">
				<span class="small-font"><%= User.find(session[:user_id]).get_api_key %></span>
			</div>
			<br />
			<b class="larger red">ily.io allows 3 ways to send API request.</b><br />
			<b class="green">Method 1, Direct link</b><br />
			You can use the API by directly accessing the following URL.<br />
			[<b class="green">Note:</b> The parameters should be in the same sequence]
			<div class="small-font framed">
				http://ily.io/api/user_id/<b>&lt; your ID &gt;</b>/api_key/<b>&lt; your API key &gt;</b>/url/<b>&lt; URL to shrink &gt;</b><br /><br />
				<b>For example,</b><br />
				http://ily.io/api/user_id/<%= session[:user_id] %>/api_key/<%= User.find(session[:user_id]).get_api_key %>/url/www.google.com<br />
				will add www.google.com to your shrink list.
			</div><br />
			<b class="green">Method 2, GET request</b><br />
			Another way is to send a simple GET request to the following URL using <b>user_id</b>, <b>api_key</b> and <b>url</b> as parameters.
			<div class="framed">
				http://ily.io/api/get</b><br /><br />
				<b>Example,</b> GET: {user_id: <%= session[:user_id] %>, api_key: foobar, url: google.com} will result in<br />
				http://ily.io/api/get?user_id=<%= session[:user_id] %>&amp;api_key=foobar&amp;url=google.com
			</div><br />
			<b class="green">Method 3, POST request</b><br />
			Finally you may also use a POST request to the following URL using <b>user_id</b>, <b>api_key</b> and <b>url</b> as parameters.
			<div class="framed">
				http://ily.io/api/post
			</div><br />
			<b class="heading">Response</b><br />
			If the operation has been successfully complete, the shrinked URL will be returned, else if any error occurs, 0 (zero) will be returned.
		</div>
	</div>
	<div class="nodisplay" id="ga_div">
		<div class="tool_title heading">Google Analytics</div>
		<div class="tool_desc">
			No need of introduction, google analytics is one of the most powerfull analytics tool available.<br />You can now use google analytics to get full statistics of your URLs.<br />
			You simply have to enter your Analytics tracker code in order to monitor your URLs.
			<div class="framed">
				<% if UserOtherDetail.find_by(user_id: session[:user_id]).nil? %>
				<%= form_for :google_analytics, url: add_google_analytics_path do |f| %>
					<%= f.text_field :tracker_code, class: "textInput" %>
					<%= f.submit "submit", class: "button" %>
				<% end %>
				<b class="green">format: UA-XXXXXXXX-X</b>
				<% else %>
				<div id="current_tracker_code_div">
					You have currently set <b><%= UserOtherDetail.find_by(user_id: session[:user_id]).tracker_code %></b> as your tracker code.<br />
					<a id="change_tracker_code" href="">Change</a>&nbsp;<b>|</b>&nbsp;
					<a id="destroy_tracker_code" href="<%= destroy_google_analytics_path %>" data-method="post">Delete</a>
				</div>
				<div id="change_tracker_code_div" class="nodisplay">
					<%= form_for :google_analytics, url: add_google_analytics_path do |f| %>
						<%= f.text_field :tracker_code, class: "textInput" %>
						<%= f.submit "submit", class: "button" %>
						<button id="cancel_tracker_change" class="button">cancel</button>
					<% end %>
					<b>format: UA-XXXXXXXX-X</b>
				</div>
				<% end %>
			</div>
		</div>
	</div>
	<div class="nodisplay" id="mls_div">
		<div class="tool_title heading">Multi-links Shrinker</div>
		<div class="tool_desc">
			Multi-links shrinker allows you to shrink up to 25 links in a single go.<br /><br />
			<b class="red">Links must be in the form</b>
			<div class="framed">
				&lt;a href="http://example.com"&gt;Example.com&lt;/a&gt;
			</div>
		</div>
		<div id="mls_tool_textarea">
			<textarea></textarea>
		</div>
		<div id="mls_shrink"><button class="button">Shrink</button></div>
	</div>
	<div class="nodisplay" id="wes_div">
		<div class="tool_title heading">Website entry script(wes)</div>
		<div class="tool_desc">
			If you owns a blog or a website and you want to make money as soon a someone access you blog/site, then this tool is a godsent.<br /><br />
			The website entry script(WES) tool allows you to divert vistors to our intersital ad system and then redirect them back to your blog/site.<br /><br />
			<div class="heading">How to inegrate WES?</div>
			You must ensure that your blog/site has jQuery integrated. The wes.js script must be after your jQuery plugin.<br />Moreover, the needed to place another initiation script just before the wes.js one.<br />
			<b>Example</b>
			<div class="framed script">
				&lt;script src="<b>to your jQuery.js</b>"&gt;&lt;/script&gt;<br />
				&lt;script&gt;<br />
				&nbsp;&nbsp;&nbsp;&nbsp;<span class="s_var">var</span> <b>ilyio_user_id</b> = <span class="s_num">2</span>;<br />
				&nbsp;&nbsp;&nbsp;&nbsp;<span class="s_var">var</span> <b>ilyio_delay</b> = <span class="s_num">5000</span>;<span class="s_comment">&nbsp;&nbsp;&nbsp;&nbsp;// in mili-seconds</span><br />
				&nbsp;&nbsp;&nbsp;&nbsp;<span class="s_var">var</span> <b>ilyio_interval</b> = <span class="s_num">5</span>;<span class="s_comment">&nbsp;&nbsp;&nbsp;&nbsp;// in minutes</span><br />
				&nbsp;&nbsp;&nbsp;&nbsp;<span class="s_var">var</span> <b>ilyio_maximum</b> = <span class="s_num">3</span>;<br />
				&lt;/script&gt;<br />
				&lt;script src="http://ily.io/assets/wes.js"&gt;&lt;/script&gt;
			</div><br />
			<div class="heading">What is the initiation script?</div>
			The initiation script allows for the proper execution of the WES.<br />
			[<b class="green">Note:</b> Preferable to leave it in its default values]<br /><br />
			<div class="red bold">Parameters</div>
			<table>
				<tr>
					<td><span class="bold blue">ilyio_user_id:</span></td>
					<td>This parameter is your user id. This parameter should not be changed.</td>
				</tr>
				<tr>
					<td><span class="bold blue">ilyio_delay:</span></td>
					<td>This parameter allows you to set the time delay(in mili-seconds) after which the visitor will be redirected to the intersital ad.</td>
				</tr>
				<tr>
					<td><span class="bold blue">ilyio_interval:</span></td>
					<td>This parameter allows you to set the time inverval(in minutes) between two intersital ad redirect for each visitor.</td>
				</tr>
				<tr>
					<td><span class="bold blue">ilyio_maximum:</span></td>
					<td>This parameter allows you to set the maximum times <b>each</b> visitor will be redirected to the intersital ad.</td>
				</tr>
			</table>
		</div>
	</div>
</div>

app/views/users/withdraw.html.erb
Withdraw