config/routes.rb
RailsSite::Application.routes.draw do

	get "test/one"
	get "test/two"
	get "test/three"
	get "test/four"
	get "intersital/index"
	namespace :deposits do
		post "form_submit"
		post "set_express_checkout_paypal"
		get "do_express_checkout_paypal"
		post "set_express_checkout_payza"
	end

	get "advertiser", to:"advertisers#index"
	get "advertiser/wallet", to:"advertisers#wallet"
	get "advertiser/wallet/page/:page_number", to:"advertisers#wallet", constraints: {:page_number => /[0-9]+/}
	get "advertiser/campaign", to:"advertisers#campaign"
	get "advertiser/create_ad", to:"advertisers#create_ad"
	post "advertiser/create_ad", as:"advertiser_create_ad_post", to:"advertisers#create_ad_post"
	post "advertiser/destroy_ad/:id", as:"advertiser_destroy_ad", to:"advertisers#destroy_ad", id: /[0-9]+/
	post "advertiser/create_ad_preview", to:"advertisers#create_ad_preview"
	get "advertiser/create_ad/design/:id", to:"advertisers#design_ad", id: /[0-9]+/, as: "advertiser_design_ad"
	post "advertiser/create_ad/design/:id", to:"advertisers#design_ad", id: /[0-9]+/, as: "advertiser_design_ad_post"
	get "advertiser/create_ad/clone/:id", to:"advertisers#clone_ad", id: /[0-9]+/, as: "advertiser_clone_ad"
	post "advertiser/create_ad/clone/:id", to:"advertisers#clone_ad", id: /[0-9]+/, as: "advertiser_clone_ad_post"
	get "advertiser/account",  to:"advertisers#account"

	resources :announcements

	get  "r/:referer_key", to: "referal#initiate", constraints:{ referer_key: /[-~_.0-9A-Za-z]{4}/ }, as: "referal_init"
	post "referal/create"
	post "referal/destroy"

	root "welcome#index"

	get   "welcome/index"
	get   ":who/learn_more", to: "welcome#learn_more", as: :welcome_learn_more, constraints: {who: /publisher|advertiser|pub|adv/}

	namespace :url_action do
		post "shrink"
		post ":id/destroy", as: :destroy, action: :destroy
		post "update_urls"
		post "mass_shrink"
		post "multi_links_shrink"
	end

	resource :users
	post  "users/login", as: "login_users"
	post  "users/logout", as: "logout_users"
	post  "user/google_analytics/add", to: "users#add_google_analytics", as: "add_google_analytics"
	post  "user/google_analytics/destroy", to: "users#destroy_google_analytics", as: "destroy_google_analytics"

	get   "u", as: "user_home", to: "users#home"
	get   "u/dashboard", to: "users#home"
	get   "u/referals", to: "users#referals"
	get   "u/tools", to: "users#tools"
	get   "u/withdraw", to: "users#withdraw"
	get   "u/account", to: "users#account"

	get  "api/user_id/:user_id/api_key/:api_key/url/*url", to: "url_action#api", constraints:{api_key: /\w{64}/, user_id: /[0-9]+/, url: /(http\:\/|https\:\/|)\w+[.]{1}\w+([.]{1}\w+|)+(\/.+|)/}, format: false
	get  "api/get", to: "url_action#api", format: false
	post "api/post", to: "url_action#api", format: false

	get "tests", to: "url_action#test"

	get  "bookmarklet/*url", to: "url_action#bookmarklet", format: false

	get  ":user_id/*url", to: "url_action#easy_link", as: "easy_link", constraints:{user_id: /[0-9]+[+]{1}/, url: /((http\:\/|https\:\/|)\w+[.]{1}\w+([.]{1}\w+|)+(\/.+|))|http:\/localhost\:3000\/tests/}, format: false
	get  ":user_id/:digest_url", to: "url_action#digest_easy_link", as: "digest_easy_link", constraints:{user_id: /[+]{1}[0-9]+/, digest_url: /\w{32}/}, format: false

	get   "intersital/generate/:id", to: "intersital#generate_ad", constraints:{ id: /[0-9]+/ }, as: :generate_intersital
	get   "intersital/generate/preview/:id", to: "intersital#generate_ad_preview", constraints:{ id: /[0-9]+/ }, as: :generate_intersital_preview
	post  "intersital/request_campaign", to: "intersital#request_campaign"
	get   ":key", to: "intersital#index", constraints:{ key: /[-~_.0-9A-Za-z]{4}/ }

end

app/models/advert.rb
class Advert < ActiveRecord::Base
	self.inheritance_column = nil
	serialize :answers, Array
	has_one :advert_detail
end

app/models/advert_detail.rb
class AdvertDetail < ActiveRecord::Base
	belongs_to :advert
	serialize :images, Array
	def get_images_array
		images.map do |image_id|
			image = Image.find image_id
			"#{image_id}_#{image.user_id}#{image.extension}"
		end
	end
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
end

app/models/deposit.rb
class Deposit < ActiveRecord::Base
	self.inheritance_column = nil

	before_validation :add_received_amount

	validates :token, uniqueness: true, presence: true
	validates :amount, :received_amount, presence: true

	private
		def add_received_amount
			self.received_amount = 0.97 * (self.amount - 0.3)
		end
end

app/models/error_log.rb
class ErrorLog < ActiveRecord::Base
end

app/models/image.rb
class Image < ActiveRecord::Base
	def get_image
		"#{self.id}_#{self.user_id}#{self.extension}"
	end
end

app/models/preview_image.rb
class PreviewImage < ActiveRecord::Base
	def get_image
		"#{self.id}_#{self.user_id}#{self.extension}"
	end
end

app/models/skip_ad_detail.rb
class SkipAdDetail < ActiveRecord::Base
end

app/models/url.rb
require 'Base66'

class Url < ActiveRecord::Base
	belongs_to :user

	before_validation :init
	after_create :add_key

	validates :target, :user_id, :views, :unique_views, presence: true
	validates :key, uniqueness: true, length: { is: 4 }, allow_nil: true

	private
		def init
			self.user_id ||= 0
			self.views ||= 0
			self.unique_views ||= 0
		end

		def add_key
			key = Base66.encode self.id
			self.update_attributes :key => key
		end
end

app/models/user.rb
require 'Base66'

class EmailValidator < ActiveModel::EachValidator
	def validate_each(record, attribute, value)
		unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
			record.errors[attribute] << (options[:message] || 'is not an email')
		end
	end
end

class PasswordValidator < ActiveModel::EachValidator
	def validate_each(record, attribute, value)
		if (value =~ /[0-9]+/).nil? || (value =~ /[a-z]+/).nil? || (value =~ /[A-Z]+/).nil?
			record.errors[attribute] << (options[:message] || "must contain at least 1 lowercase, 1 uppercase and 1 number")
		end
	end
end

class User < ActiveRecord::Base
	has_many :url

	after_create :digest_password
	validates :full_name, :email, :password, presence: true
	validates :full_name, length: { in: 5..50 }
	validates :email, uniqueness: true, email: true
	### Create validation for password ###

	def get_api_key
		if api_key.nil?
			api_key_ = Digest::MD5.hexdigest "USER_ID=#{id}&TIMESTAMP=#{Time.now.to_s}&RAND_NUM=#{Random.new.rand(1000)}"
			update api_key: api_key_
		else
			api_key_ = api_key
		end
		api_key_
	end

	private
		def digest_password
			update password: Digest::MD5.hexdigest(self.password)
		end
end

app/models/user_other_detail.rb
class UserOtherDetail < ActiveRecord::Base
end

app/controllers/test_controller.rb
class TestController < ApplicationController
	def one
		flash[:one] = { name: "Akhilesh", age: 18 }
		redirect_to test_two_path
	end

	def two
		if flash[:one].nil?
			render text: "0k"
		else
			render text: "N0t 0k"
		end
	end

	def three
		redirect_to advertiser_design_ad_path 9
	end

	def four
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :login_check, only: [:index]
  before_action :redirect_to_https, only: [:index]
  def index
  	@user = User.new
  end

  def learn_more
  	@who = params[:who]
  	if @who == "publisher" || @who == "pub"

  	elsif @who  == "advertiser" || @who == "adv"

  	else
  		flash[:error] = "Invalid url"
  		redirect_to root_path
  	end
  end

  private

    def login_check
      unless session[:user_id].nil?
        redirect_to user_home_path
      end
    end

end

app/helpers/advertisers_helper.rb
module AdvertisersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deposits_helper.rb
module DepositsHelper
end

app/helpers/intersital_helper.rb
module IntersitalHelper
end

app/helpers/referal_helper.rb
module ReferalHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/url_action_helper.rb
module UrlActionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<header>
	<div>Ily.io</div>
	<div>Shorten Urls Make Money Now !</div>
</header>

<div id="body">
	<div>
		<div id="description">
			<div class="heading center" style="font-size:2em;">What is Ily.io</div>
			<div>
				<table id="desc">
					<tbody>
						<tr>
							<td class="heading">For Publishers..!</td>
							<td class="heading">For Advertisers..!</td>
						</tr>
						<tr>
							<td class="elclassico">
								Shorten urls make money now ! Share your short links and get paid. Publishers enjnoys an <strong>amazing fixed</strong> rate of <strong>$10.00 per 1000</strong> US views.<br />Thats damn co0l..! <%= link_to "Learn More", welcome_learn_more_path(:publisher) %>
							</td>
							<td class="elclassico">
								Ily.io have developped a <strong>never seen before</strong> advertising technique. Ily.io ensure that over <strong>99%</strong> of visitors will see and <strong>understand</strong> your ad.<br />How is it done..? <%= link_to "Learn More", welcome_learn_more_path(:advertiser) %>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>

		<div id="middle">
			<div>
				<table class="display">
					<tr>
						<td>
							<span>
								Login<br />
								or<br />
								Register
							</span>
						</td>
						<td>
							&gt;
						</td>
					</tr>
				</table>

				<table class="nodisplay">
					<tr>
						<td>
							&lt;
						</td>
						<td>
							<span>
								what is<br />Ily.io<br />??
							</span>
						</td>
					</tr>
				</table>

			</div>
		</div>

		<div id="loginRegister">
			<div class="heading center" style="font-size:2em;">Login or Register</div>
			<table id="logreg">
				<tbody>
					<tr>
						<td class="heading">Login !</td>
						<td class="heading">Register !</td>
					</tr>
					<tr>
						<td>
							<%= form_for :user_login, url: login_users_path, html: { id: "login_form" } do |f| %>
							<table>
								<tbody>
									<tr>
										<td><span><%= f.label :email %></span></td>
										<td><span><%= f.email_field :email, class: "textInput" %></span></td>
									</tr>
									<tr>
										<td><span><%= f.label :password %></span></td>
										<td><span><%= f.password_field :password, class: "textInput" %></span></td>
									</tr>
									<tr>
										<td></td>
										<td><span><%= f.submit "log in", class: "button" %></span></td>
									</tr>
								</tbody>
							</table>
							<% end %>
						</td>
						<td>
							<%= form_for :user_register, url: users_path, html: { id: "register_form" } do |f| %>
							<table>
								<tbody>
									<tr>
										<td><span><%= f.label :full_name, "Full name" %></span></td>
										<td><span><%= f.text_field :full_name, class: "textInput" %></span></td>
									</tr>
									<tr>
										<td><span><%= f.label :email %></span></td>
										<td><span><%= f.email_field :email, class: "textInput" %></span></td>
									</tr>
									<tr>
										<td><span><%= f.label :password %></span></td>
										<td><span><%= f.password_field :password, class: "textInput" %></span></td>
									</tr>
									<tr>
										<td><span><%= f.label :repassword, "Retype password" %></span></td>
										<td><span><%= f.password_field :repassword, class: "textInput" %></span></td>
									</tr>
									<tr>
										<td></td>
										<td><span><%= f.submit "sign up", class: "button" %></span></td>
									</tr>
								</tbody>
							</table>
							<% end %>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	
</div>
<div id="tryit">
	<div class="heading">Try it out</div>
	<div>
		<%= form_for :shrink, url: url_action_shrink_path, html:{ id: "try_it" } do |f| %>
			<div>
				<div><%= f.text_field :target, class: "textInput", placeholder: "http://" %></div>
				<div><%= f.submit "Shrink", class: "button" %></div>
				<div></div>
				<div></div>
			</div>
		<% end %>
	</div>
</div>
<footer>
	<div>
		<div><i>ily.io &copy; <%= Time.now.year %></i>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;Made with <span id="heart">&hearts;</span> in Mauritius, Mah&eacute;bourg... :*<span id="jai_sri_krsna">&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;जय श्री कृष्ण</span></div>
		<hr />
		<div>
			<table>
				<tr>
					<td><a href="">{ Publisher Rates }</a></td>
					<td><a href="">{ About us }</a></td>
				</tr>
				<tr>
					<td><a href="">{ Advertiser Rates }</a></td>
					<td><a href="">{ terms &amp; policies}</a></td>
				</tr>
				<tr>
					<td><%= link_to"{ Publisher:Learn more }", welcome_learn_more_path(:pub) %></td>
					<td><a href="">{ help }</a></td>
				</tr>
				<tr>
					<td><%= link_to "{ Advertiser:Learn more }", welcome_learn_more_path(:adv) %></td>
					<td><a href="">{ like us on fb }</a></td>
				</tr>
			</table>
		</div>
	</div>
</footer>

app/views/welcome/learn_more.html.erb
<h1>Welcome#learn_more</h1>
<p>Find me in app/views/welcome/learn_more.html.erb</p>
<%= @who %>