config/routes.rb
RailsSite::Application.routes.draw do

	get "test/one"
	get "test/two"
	get "test/three"
	get "test/four"
	get "intersital/index"
	namespace :deposits do
		post "form_submit"
		post "set_express_checkout_paypal"
		get "do_express_checkout_paypal"
		post "set_express_checkout_payza"
	end

	get "advertiser", to:"advertisers#index"
	get "advertiser/wallet", to:"advertisers#wallet"
	get "advertiser/wallet/page/:page_number", to:"advertisers#wallet", constraints: {:page_number => /[0-9]+/}
	get "advertiser/campaign", to:"advertisers#campaign"
	get "advertiser/create_ad", to:"advertisers#create_ad"
	post "advertiser/create_ad", as:"advertiser_create_ad_post", to:"advertisers#create_ad_post"
	post "advertiser/destroy_ad/:id", as:"advertiser_destroy_ad", to:"advertisers#destroy_ad", id: /[0-9]+/
	post "advertiser/create_ad_preview", to:"advertisers#create_ad_preview"
	get "advertiser/create_ad/design/:id", to:"advertisers#design_ad", id: /[0-9]+/, as: "advertiser_design_ad"
	post "advertiser/create_ad/design/:id", to:"advertisers#design_ad", id: /[0-9]+/, as: "advertiser_design_ad_post"
	get "advertiser/create_ad/clone/:id", to:"advertisers#clone_ad", id: /[0-9]+/, as: "advertiser_clone_ad"
	post "advertiser/create_ad/clone/:id", to:"advertisers#clone_ad", id: /[0-9]+/, as: "advertiser_clone_ad_post"
	get "advertiser/account",  to:"advertisers#account"

	resources :announcements

	get  "r/:referer_key", to: "referal#initiate", constraints:{ referer_key: /[-~_.0-9A-Za-z]{4}/ }, as: "referal_init"
	post "referal/create"
	post "referal/destroy"

	root "welcome#index"

	get   "welcome/index"
	get   ":who/learn_more", to: "welcome#learn_more", as: :welcome_learn_more, constraints: {who: /publisher|advertiser|pub|adv/}

	namespace :url_action do
		post "shrink"
		post ":id/destroy", as: :destroy, action: :destroy
		post "update_urls"
		post "mass_shrink"
		post "multi_links_shrink"
	end

	resource :users
	post  "users/login", as: "login_users"
	post  "users/logout", as: "logout_users"
	post  "user/google_analytics/add", to: "users#add_google_analytics", as: "add_google_analytics"
	post  "user/google_analytics/destroy", to: "users#destroy_google_analytics", as: "destroy_google_analytics"

	get   "u", as: "user_home", to: "users#home"
	get   "u/dashboard", to: "users#home"
	get   "u/referals", to: "users#referals"
	get   "u/tools", to: "users#tools"
	get   "u/withdraw", to: "users#withdraw"
	get   "u/account", to: "users#account"

	get  "api/user_id/:user_id/api_key/:api_key/url/*url", to: "url_action#api", constraints:{api_key: /\w{64}/, user_id: /[0-9]+/, url: /(http\:\/|https\:\/|)\w+[.]{1}\w+([.]{1}\w+|)+(\/.+|)/}, format: false
	get  "api/get", to: "url_action#api", format: false
	post "api/post", to: "url_action#api", format: false

	get "tests", to: "url_action#test"

	get  "bookmarklet/*url", to: "url_action#bookmarklet", format: false

	get  ":user_id/*url", to: "url_action#easy_link", as: "easy_link", constraints:{user_id: /[0-9]+[+]{1}/, url: /((http\:\/|https\:\/|)\w+[.]{1}\w+([.]{1}\w+|)+(\/.+|))|http:\/localhost\:3000\/tests/}, format: false
	get  ":user_id/:digest_url", to: "url_action#digest_easy_link", as: "digest_easy_link", constraints:{user_id: /[+]{1}[0-9]+/, digest_url: /\w{32}/}, format: false

	get   "intersital/generate/:id", to: "intersital#generate_ad", constraints:{ id: /[0-9]+/ }, as: :generate_intersital
	get   "intersital/generate/preview/:id", to: "intersital#generate_ad_preview", constraints:{ id: /[0-9]+/ }, as: :generate_intersital_preview
	post  "intersital/request_campaign", to: "intersital#request_campaign"
	get   ":key", to: "intersital#index", constraints:{ key: /[-~_.0-9A-Za-z]{4}/ }

end

app/models/advert.rb
class Advert < ActiveRecord::Base
	self.inheritance_column = nil
	serialize :answers, Array
	has_one :advert_detail
end

app/models/advert_detail.rb
class AdvertDetail < ActiveRecord::Base
	belongs_to :advert
	serialize :images, Array
	def get_images_array
		images.map do |image_id|
			image = Image.find image_id
			"#{image_id}_#{image.user_id}#{image.extension}"
		end
	end
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
end

app/models/deposit.rb
class Deposit < ActiveRecord::Base
	self.inheritance_column = nil

	before_validation :add_received_amount

	validates :token, uniqueness: true, presence: true
	validates :amount, :received_amount, presence: true

	private
		def add_received_amount
			self.received_amount = 0.97 * (self.amount - 0.3)
		end
end

app/models/error_log.rb
class ErrorLog < ActiveRecord::Base
end

app/models/image.rb
class Image < ActiveRecord::Base
	def get_image
		"#{self.id}_#{self.user_id}#{self.extension}"
	end
end

app/models/preview_image.rb
class PreviewImage < ActiveRecord::Base
	def get_image
		"#{self.id}_#{self.user_id}#{self.extension}"
	end
end

app/models/skip_ad_detail.rb
class SkipAdDetail < ActiveRecord::Base
end

app/models/url.rb
require 'Base66'

class Url < ActiveRecord::Base
	belongs_to :user

	before_validation :init
	after_create :add_key

	validates :target, :user_id, :views, :unique_views, presence: true
	validates :key, uniqueness: true, length: { is: 4 }, allow_nil: true

	private
		def init
			self.user_id ||= 0
			self.views ||= 0
			self.unique_views ||= 0
		end

		def add_key
			key = Base66.encode self.id
			self.update_attributes :key => key
		end
end

app/models/user.rb
require 'Base66'

class EmailValidator < ActiveModel::EachValidator
	def validate_each(record, attribute, value)
		unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
			record.errors[attribute] << (options[:message] || 'is not an email')
		end
	end
end

class PasswordValidator < ActiveModel::EachValidator
	def validate_each(record, attribute, value)
		if (value =~ /[0-9]+/).nil? || (value =~ /[a-z]+/).nil? || (value =~ /[A-Z]+/).nil?
			record.errors[attribute] << (options[:message] || "must contain at least 1 lowercase, 1 uppercase and 1 number")
		end
	end
end

class User < ActiveRecord::Base
	has_many :url

	after_create :digest_password
	validates :full_name, :email, :password, presence: true
	validates :full_name, length: { in: 5..50 }
	validates :email, uniqueness: true, email: true
	### Create validation for password ###

	def get_api_key
		if api_key.nil?
			api_key_ = Digest::MD5.hexdigest "USER_ID=#{id}&TIMESTAMP=#{Time.now.to_s}&RAND_NUM=#{Random.new.rand(1000)}"
			update api_key: api_key_
		else
			api_key_ = api_key
		end
		api_key_
	end

	private
		def digest_password
			update password: Digest::MD5.hexdigest(self.password)
		end
end

app/models/user_other_detail.rb
class UserOtherDetail < ActiveRecord::Base
end

app/helpers/advertisers_helper.rb
module AdvertisersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deposits_helper.rb
module DepositsHelper
end

app/helpers/intersital_helper.rb
module IntersitalHelper
end

app/helpers/referal_helper.rb
module ReferalHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/url_action_helper.rb
module UrlActionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/advertisers.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= @layout_details[:title].nil? ? 'ily.io' : @layout_details[:title] %></title>
        <%= stylesheet_link_tag "ily.io" %>
        <%= javascript_include_tag "jquery-1.11.1.min" %>
        <%= javascript_include_tag "apprise-v2" %>
        <%= stylesheet_link_tag "apprise-v2" %>
        <%= javascript_include_tag "jquery.zclip" %>
        <%= javascript_include_tag "ily.io" %>
        <% unless @layout_details.nil? %>
            <%= @layout_details[:controller].nil? ? nil : stylesheet_link_tag("#{@layout_details[:controller]}") %>
            <%= @layout_details[:action].nil? ? nil : stylesheet_link_tag("#{@layout_details[:controller]}/#{@layout_details[:action]}") %>
            <% @layout_details[:other_styles].each do |style| %>
                <%= stylesheet_link_tag style %>
            <% end %>
            <%= @layout_details[:controller].nil? ? nil : javascript_include_tag("#{@layout_details[:controller]}") %>
            <%= @layout_details[:action].nil? ? nil : javascript_include_tag("#{@layout_details[:controller]}/#{@layout_details[:action]}") %>
            <% @layout_details[:other_scripts].each do |script| %>
                <%= javascript_include_tag script %>
            <% end %>
        <% end %>
        <%= javascript_tag do %>
            <% if flash[:alerts].nil? && flash[:errors].nil? %>
                window.alert_any = false
            <% else %>
                window.alert_any = true
                window.alert_desc = "<%= j h flash[:alerts].nil? ? flash[:errors] : flash[:errors] %>"
            <% end %>
        <% end %>
        <link rel="icon" type="image/ico" href="<%= image_path "favicon.ico" %>"/>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <header>
            <img src="<%= image_path("ily.io.png") %>">
        </header>
        <div id="body">
            <form id="form"></form> <!-- needed to logout -->
            <div id="menu">
                <%= render "partials/#{@layout_details[:controller]}_navbar" %>
            </div>
            <div id="content">
                <%= yield %>
            </div>
            <aside id="invisibles">
            </aside>
        </div>
        <footer>
            <div>
                <div><i>ily.io &copy; <%= Time.now.year %></i>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;Made with <span id="heart">&hearts;</span> in Mauritius, Mah&eacute;bourg... :*<span id="jai_sri_krsna">&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;जय श्री कृष्ण</span></div>
                <hr />
                <div>
                    <table>
                        <tr>
                            <td><a href="">{ Publisher Rates }</a></td>
                            <td><a href="">{ About us }</a></td>
                        </tr>
                        <tr>
                            <td><a href="">{ Advertiser Rates }</a></td>
                            <td><a href="">{ terms &amp; policies}</a></td>
                        </tr>
                        <tr>
                            <td><%= link_to"{ Publisher:Learn more }", welcome_learn_more_path(:pub) %></td>
                            <td><a href="">{ help }</a></td>
                        </tr>
                        <tr>
                            <td><%= link_to "{ Advertiser:Learn more }", welcome_learn_more_path(:adv) %></td>
                            <td><a href="">{ like us on fb }</a></td>
                        </tr>
                    </table>
                </div>
            </div>
        </footer>
    </body>
</html>

app/views/layouts/announcements.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsSite</title>
  <%= stylesheet_link_tag    "scaffolds" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsSite</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/intersital.html.erb
<!DOCTYPE html>
<html>
	<head>
        <title><%= @layout_details[:title].nil? ? 'ily.io' : @layout_details[:title] %></title>
        <%= stylesheet_link_tag "ily.io" %>
        <%= javascript_include_tag "jquery-1.11.1.min" %>
        <%= javascript_include_tag "apprise-v2" %>
        <%= stylesheet_link_tag "apprise-v2" %>
        <%= javascript_include_tag "jquery.zclip" %>
        <%= javascript_include_tag "ily.io" %>
        <% unless @layout_details.nil? %>
            <%= @layout_details[:controller].nil? ? nil : stylesheet_link_tag("#{@layout_details[:controller]}") %>
            <%= @layout_details[:action].nil? ? nil : stylesheet_link_tag("#{@layout_details[:controller]}/#{@layout_details[:action]}") %>
            <% @layout_details[:other_styles].each do |style| %>
                <%= stylesheet_link_tag style %>
            <% end %>
            <%= @layout_details[:controller].nil? ? nil : javascript_include_tag("#{@layout_details[:controller]}") %>
            <%= @layout_details[:action].nil? ? nil : javascript_include_tag("#{@layout_details[:controller]}/#{@layout_details[:action]}") %>
            <% @layout_details[:other_scripts].each do |script| %>
                <%= javascript_include_tag script %>
            <% end %>
        <% end %>
        <%= javascript_tag do %>
            <% if flash[:alerts].nil? && flash[:errors].nil? %>
                window.alert_any = false
            <% else %>
                window.alert_any = true
                window.alert_desc = "<%= j h flash[:alerts].nil? ? flash[:errors] : flash[:errors] %>"
            <% end %>
        <% end %>
        <link rel="icon" type="image/ico" href="<%= image_path "favicon.ico" %>"/>
        <%= csrf_meta_tags %>
	</head>

	<body>
		<div id="overlay">
			<header>
				<div>
					<div>
					    <div>
					        <div>
					            <img data-url="<%= root_path %>" src="<%= image_path("ily.io.png") %>">
					        </div>
					    </div>
					    <div class="red" id="countdown_div">
							Please analyse the advert below for <span class="bold largest" id="countdown_span">30</span> seconds<br />
							Then proceed to your link
					    </div>
						<div>
							<button disabled class="button" id="goto_site">Proceed to site &nbsp;&rightarrow;</button>
						</div>
					</div>
				</div>
			</header>
			<div id='vertical_bar_div'></div>
		    <form id="form" method="post"></form>
			<div id="body">
			<%= yield %>
			</div>
		</div>
        <div id="question_answer_outer_div">
            <div id="question_answer_inner_div">
				<div id="question_answer_inner_inner_div">
					<div class="heading green center" style="padding: 0 0 10px 0">Just answer this question and unlock your link !</div>
					<div class="heading" id="question_div">Unknown Error !</div>
					<div class="ubuntu" id="answers_div">
					</div>
				</div>
            </div>
        </div>
		<div class="bold ubuntu" id="question_answer_div_close">
			close&nbsp;X
		</div>
	</body>
</html>

app/views/layouts/no_menu.html.erb
<!DOCTYPE html>
<html>
<head>
    <title><%= @layout_details[:title].nil? ? 'ily.io' : @layout_details[:title] %></title>
    <%= stylesheet_link_tag "ily.io" %>
    <%= javascript_include_tag "jquery-1.11.1.min" %>
    <%= javascript_include_tag "apprise-v2" %>
    <%= stylesheet_link_tag "apprise-v2" %>
    <%= javascript_include_tag "jquery.zclip" %>
    <%= javascript_include_tag "ily.io" %>
    <% unless @layout_details.nil? %>
        <%= @layout_details[:controller].nil? ? nil : stylesheet_link_tag("#{@layout_details[:controller]}") %>
        <%= @layout_details[:action].nil? ? nil : stylesheet_link_tag("#{@layout_details[:controller]}/#{@layout_details[:action]}") %>
        <% @layout_details[:other_styles].each do |style| %>
            <%= stylesheet_link_tag style %>
        <% end %>
        <%= @layout_details[:controller].nil? ? nil : javascript_include_tag("#{@layout_details[:controller]}") %>
        <%= @layout_details[:action].nil? ? nil : javascript_include_tag("#{@layout_details[:controller]}/#{@layout_details[:action]}") %>
        <% @layout_details[:other_scripts].each do |script| %>
            <%= javascript_include_tag script %>
        <% end %>
    <% end %>
    <%= javascript_tag do %>
        <% if flash[:alerts].nil? && flash[:errors].nil? %>
            window.alert_any = false
        <% else %>
            window.alert_any = true
            window.alert_desc = "<%= j h flash[:alerts].nil? ? flash[:errors] : flash[:errors] %>"
        <% end %>
        <% unless flash[:preview_ad_id].nil? %>
            window.preview_link = "<%= generate_intersital_preview_path params[:id] %>";
        <% end %>
    <% end %>
    <link rel="icon" type="image/ico" href="<%= image_path "favicon.ico" %>"/>
    <%= csrf_meta_tags %>
</head>
<body>
<header>
    <img src="<%= image_path("ily.io.png") %>">
</header>
<div id="body">
    <form id="form"></form> <!-- needed to logout -->
    <div id="menu">
        <%= render "partials/#{@layout_details[:controller]}_navbar" %>
    </div>
    <div id="content">
        <%= yield %>
    </div>
    <aside id="invisibles">
    </aside>
</div>
<footer>
    <div>
        <div><i>ily.io &copy; <%= Time.now.year %></i>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;Made with <span id="heart">&hearts;</span> in Mauritius, Mah&eacute;bourg... :*<span id="jai_sri_krsna">&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;जय श्री कृष्ण</span></div>
        <hr />
        <div>
            <table>
                <tr>
                    <td><a href="">{ Publisher Rates }</a></td>
                    <td><a href="">{ About us }</a></td>
                </tr>
                <tr>
                    <td><a href="">{ Advertiser Rates }</a></td>
                    <td><a href="">{ terms &amp; policies}</a></td>
                </tr>
                <tr>
                    <td><%= link_to"{ Publisher:Learn more }", welcome_learn_more_path(:pub) %></td>
                    <td><a href="">{ help }</a></td>
                </tr>
                <tr>
                    <td><%= link_to "{ Advertiser:Learn more }", welcome_learn_more_path(:adv) %></td>
                    <td><a href="">{ like us on fb }</a></td>
                </tr>
            </table>
        </div>
    </div>
</footer>
<% unless flash[:preview_ad_id].nil? %>
<div style="display:none" id="preview_div">
<div><img src="<%= image_path "16.GIF" %>"><iframe id="ad_iframe"></iframe></div>
</div>
<div class="bold ubuntu" style="display:none" id="preview_div_close">
	close&nbsp;X
</div>
<% end %>

<div style="display:none" id="image_div">
<div><img src="<%= image_path "16.GIF" %>" /><img src="" /></div>
</div>
<div class="bold ubuntu" style="display:none" id="image_div_close">
	close&nbsp;X
</div>

</body>
</html>

app/views/layouts/plain_with_background.html.erb
<!DOCTYPE html>
<html>
	<head>
        <title><%= @layout_details[:title].nil? ? 'ily.io' : @layout_details[:title] %></title>
        <%= stylesheet_link_tag "ily.io" %>
        <%= javascript_include_tag "jquery-1.11.1.min" %>
        <%= javascript_include_tag "apprise-v2" %>
        <%= stylesheet_link_tag "apprise-v2" %>
        <%= javascript_include_tag "jquery.zclip" %>
        <%= javascript_include_tag "ily.io" %>
        <% unless @layout_details.nil? %>
            <%= @layout_details[:controller].nil? ? nil : stylesheet_link_tag("#{@layout_details[:controller]}") %>
            <%= @layout_details[:action].nil? ? nil : stylesheet_link_tag("#{@layout_details[:controller]}/#{@layout_details[:action]}") %>
            <% @layout_details[:other_styles].each do |style| %>
                <%= stylesheet_link_tag style %>
            <% end %>
            <%= @layout_details[:controller].nil? ? nil : javascript_include_tag("#{@layout_details[:controller]}") %>
            <%= @layout_details[:action].nil? ? nil : javascript_include_tag("#{@layout_details[:controller]}/#{@layout_details[:action]}") %>
            <% @layout_details[:other_scripts].each do |script| %>
                <%= javascript_include_tag script %>
            <% end %>
        <% end %>
        <%= javascript_tag do %>
            <% if flash[:alerts].nil? && flash[:errors].nil? %>
                window.alert_any = false
            <% else %>
                window.alert_any = true
                window.alert_desc = "<%= j h flash[:alerts].nil? ? flash[:errors] : flash[:errors] %>"
            <% end %>
        <% end %>
        <link rel="icon" type="image/ico" href="<%= image_path "favicon.ico" %>"/>
        <%= csrf_meta_tags %>
	</head>

	<body>
		<div id="body">
			<form id="form"></form> <!-- needed to logout -->

			<div id="content">
				<%= yield %>
			</div>
		</div>

		<aside id="invisibles">
		</aside>
	</body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= @layout_details[:title].nil? ? 'ily.io' : @layout_details[:title] %></title>
		<%= stylesheet_link_tag "ily.io" %>
		<%= javascript_include_tag "jquery-1.11.1.min" %>
	    <%= javascript_include_tag "apprise-v2" %>
	    <%= stylesheet_link_tag "apprise-v2" %>
		<%= javascript_include_tag "jquery.zclip" %>
		<%= javascript_include_tag "ily.io" %>
        <% unless @layout_details.nil? %>
            <%= @layout_details[:controller].nil? ? nil : stylesheet_link_tag("#{@layout_details[:controller]}") %>
            <%= @layout_details[:action].nil? ? nil : stylesheet_link_tag("#{@layout_details[:controller]}/#{@layout_details[:action]}") %>
            <% @layout_details[:other_styles].each do |style| %>
                <%= stylesheet_link_tag style %>
            <% end %>
            <%= @layout_details[:controller].nil? ? nil : javascript_include_tag("#{@layout_details[:controller]}") %>
            <%= @layout_details[:action].nil? ? nil : javascript_include_tag("#{@layout_details[:controller]}/#{@layout_details[:action]}") %>
            <% @layout_details[:other_scripts].each do |script| %>
                <%= javascript_include_tag script %>
            <% end %>
        <% end %>
	    <%= javascript_tag do %>
	        <% if flash[:alerts].nil? && flash[:errors].nil? %>
	            window.alert_any = false
	        <% else %>
	            window.alert_any = true
	            window.alert_desc = "<%= j h flash[:alerts].nil? ? flash[:errors] : flash[:errors] %>"
	        <% end %>
	    <% end %>
		<link rel="icon" type="image/ico" href="<%= image_path "favicon.ico" %>"/>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<header>
			<img src="<%= image_path("ily.io.png") %>">
		</header>
		<div id="body">
			<form id="form"></form> <!-- needed to logout -->
			<div id="menu">
			    <%= render "partials/#{@layout_details[:controller]}_navbar" %>
			</div>
			<div id="content">
				<%= yield %>
			</div>
			<aside id="invisibles">
			</aside>
		</div>
		<footer>
			<div>
				<div><i>ily.io &copy; <%= Time.now.year %></i>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;Made with <span id="heart">&hearts;</span> in Mauritius, Mah&eacute;bourg... :*<span id="jai_sri_krsna">&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;जय श्री कृष्ण</span></div>
				<hr />
				<div>
					<table>
						<tr>
							<td><a href="">{ Publisher Rates }</a></td>
							<td><a href="">{ About us }</a></td>
						</tr>
						<tr>
							<td><a href="">{ Advertiser Rates }</a></td>
							<td><a href="">{ terms &amp; policies}</a></td>
						</tr>
						<tr>
							<td><%= link_to"{ Publisher:Learn more }", welcome_learn_more_path(:pub) %></td>
							<td><a href="">{ help }</a></td>
						</tr>
						<tr>
							<td><%= link_to "{ Advertiser:Learn more }", welcome_learn_more_path(:adv) %></td>
							<td><a href="">{ like us on fb }</a></td>
						</tr>
					</table>
				</div>
			</div>
		</footer>
	</body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Sum.mn</title>
		<%= stylesheet_link_tag "ily.io" %>
		<%= stylesheet_link_tag    "welcome" %>
		<link rel="icon" type="image/ico" href="<%= image_path "favicon.ico" %>"/>
		<%= javascript_include_tag "jquery-1.11.1.min" %>
		<%= javascript_include_tag "apprise-v2" %>
		<%= stylesheet_link_tag "apprise-v2" %>
		<%= javascript_include_tag "welcome" %>
		<%= csrf_meta_tags %>
		<%= javascript_tag do %>
			<% if !flash[:error].nil? %>
				window.error_any = true
				window.error_desc = "<span class='ubuntu black large'>"+"<%= j flash[:error] %>".replace(/&lt;/g, "<").replace(/&gt;/g, ">")+"</span>"
			<% else %>
				window.error_any = false
			<% end %>
		<% end %>
		
	</head>

	<body>

	<%= yield %>

	</body>
</html>

app/views/partials/_advertisers_navbar.html.erb
<table>
    <tr>
        <td><div class="choices<%= @layout_details[:action] == "index" ? " selected" : "" %>" data-url="<%= advertiser_path %>">Dashboard</div></td>
        <td><div class="choices<%= @layout_details[:action] == "wallet" ? " selected" : "" %>" data-url="<%= advertiser_wallet_path %>">Wallet</div></td>
        <td><div class="choices<%= @layout_details[:action] == "create_ad" ? " selected" : "" %>" data-url="<%= advertiser_create_ad_path %>">Create Ad</div></td>
        <td><div class="choices<%= @layout_details[:action] == "campaign" ? " selected" : "" %>" data-url="<%= advertiser_campaign_path %>">Campaign</div></td>
        <td><div class="choices<%= @layout_details[:action] == "account" ? " selected" : "" %>" data-url="<%= advertiser_account_path %>">Account</div></td>
        <td>
            <div id="user_det_panel">
                Hello, <strong><%= @name %></strong> ! (<b><a id="logout" href="<%= logout_users_path %>" data-method="post">logout</a></b>)
            </div>
        </td>
    </tr>
</table>

app/views/partials/_users_navbar.html.erb
<table>
    <tr>
        <td><div class="choices<%= @layout_details[:action] == "home" ? " selected" : "" %>" data-url="<%= user_home_path %>">Dashboard</div></td>
        <td><div class="choices<%= @layout_details[:action] == "referal" ? " selected" : "" %>" data-url="<%= u_referals_path %>">Referrals</div></td>
        <td><div class="choices<%= @layout_details[:action] == "tools" ? " selected" : "" %>" data-url="<%= u_tools_path %>">Tools</div></td>
        <td><div class="choices<%= @layout_details[:action] == "withdraw" ? " selected" : "" %>" data-url="<%= u_withdraw_path %>">Withdraw</div></td>
        <td><div class="choices<%= @layout_details[:action] == "account" ? " selected" : "" %>" data-url="<%= u_account_path %>">Account</div></td>
        <td>
            <div id="user_det_panel">
                Hello, <strong><%= @name %></strong> ! (<b><a id="logout" href="<%= logout_users_path %>" data-method="post">logout</a></b>)
            </div>
        </td>
    </tr>
</table>